#!/bin/sh
set -e


if [ "$1" = "configure" ]; then

        # Create the "Log.io" user
        if ! getent passwd log.io > /dev/null; then

            adduser --system --group --home /usr/lib/log.io  \
                --gecos "Log.io NodeJS log transporter daemon" \
                --force-badname \
                log.io

            usermod -g daemon -G adm -a log.io
        fi

        # Set Permissions
        install --owner log.io --group adm --directory \
                    /var/log/log.io
        install --owner log.io --group daemon --directory \
                    /var/run/log.io \
                    /usr/lib/log.io \
                    /etc/log.io

fi
