#!/bin/sh
set -e

## Create Specific User to Run Log.io services
id log.io
if [ $? != 0 ] ; then
  adduser --system --home /usr/lib/log.io --force-badname log.io
  usermod -g daemon -G adm -a log.io
fi
